name: "Build Unity Project Action"
description: "Used for building an Unity project. Supports cross-platform."
author: "Neo Chen"

inputs:
  unity_install_dir:
    description: "Root directory to locate Unity installations. Defaults to the OS-specific Unity installation path. Avoid specifying a direct path to a specific Unity version."
  project_path:
    description: "Absolute path to the Unity project directory that you want to build. This should include 'ProjectSettings' folder."
    required: true
  build_method:
    description: "The fully qualified name of the Unity build method to execute, typically in the format 'Namespace.Class.Method'. This method will be invoked to start the build process."
    required: true
  build_version:
    description: "Version number for the build. This is used to label the generated logs."
  output_dir:
    description: "Relative path to the project_path where the build output will be stored. If not specified, the build output will be stored in the project directory."
    default: "Build/Releases"
  log_name:
    description: "Base name for the log file generated during the build. If not specified, a default name will be used."
    default: "build_log"
  custom_options:
    description: "Additional command line arguments passed to Unity. Each parameter should start with a dash. If an argument requires a value, place the value directly after the argument, separated by a space."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Build Unity Project
      env:
        unity_install_dir: ${{ inputs.unity_install_dir }}
        project_path: ${{ inputs.project_path }}
        build_method: ${{ inputs.build_method }}
        build_version: ${{ inputs.build_version }}
        output_dir: ${{ inputs.output_dir }}
        log_name: ${{ inputs.log_name }}
        custom_options: ${{ inputs.custom_options }}
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
      run: node ${{ github.action_path }}/build-unity-project.js